import "core-js/shim"
export * from "./Model"
export {default as Model} from "./Model"
export {default as Query} from "./Query"
export {default as Collection} from "./Collection"
export * from "./decorators"
